// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFaz4SyWjCknG0VQOhDA8epXqWw32MY5g',
    appId: '1:171374754843:web:a56ca2e23a73ffc2cc4cbe',
    messagingSenderId: '171374754843',
    projectId: 'islamic-spotify',
    authDomain: 'islamic-spotify.firebaseapp.com',
    storageBucket: 'islamic-spotify.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0aPc8FN-8dVJ-2lKUWykhQjdBc-CnS0c',
    appId: '1:171374754843:android:aeeb78844f4a371dcc4cbe',
    messagingSenderId: '171374754843',
    projectId: 'islamic-spotify',
    storageBucket: 'islamic-spotify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNT9M4RgCAHnqenY-qYDQ4awe2jAHDZCY',
    appId: '1:171374754843:ios:542f94bce6374f9dcc4cbe',
    messagingSenderId: '171374754843',
    projectId: 'islamic-spotify',
    storageBucket: 'islamic-spotify.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNT9M4RgCAHnqenY-qYDQ4awe2jAHDZCY',
    appId: '1:171374754843:ios:542f94bce6374f9dcc4cbe',
    messagingSenderId: '171374754843',
    projectId: 'islamic-spotify',
    storageBucket: 'islamic-spotify.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFaz4SyWjCknG0VQOhDA8epXqWw32MY5g',
    appId: '1:171374754843:web:880e0f26480ffb9ccc4cbe',
    messagingSenderId: '171374754843',
    projectId: 'islamic-spotify',
    authDomain: 'islamic-spotify.firebaseapp.com',
    storageBucket: 'islamic-spotify.firebasestorage.app',
  );
}
